name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build on ${{ matrix.os }} using ${{ matrix.compiler }}
    strategy:
      matrix:
        compiler:
          - g++
          - clang
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/.build -G Ninja -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build
        run: cmake --build ${{ github.workspace }}/.build --config ${{ env.BUILD_TYPE }}
      - name: Test
        working-directory: ${{ github.workspace }}/.build
        run: ctest -C ${{ env.BUILD_TYPE }}
